---
#networks:
#  frontend:
#    external: true
#  backend:
#    external: true
services:
  traefik:
    container_name: traefik-prod-1
    image: traefik:2.10.4
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./config/traefik.yml:/etc/traefik/traefik.yml:ro
      - ./config/conf/:/etc/traefik/conf/
      - ./config/certs/:/etc/traefik/certs/
    #environment:
    #  - CF_DNS_API_TOKEN=$CF_DNS_API_TOKEN # not needed with TLS challange
    #networks:
    #  - frontend
    #  - backend
    restart: unless-stopped

  whoami:
    image: nginx #"traefik/whoami"
    container_name: "simple-service"
    ports:
      - "8081:80"
    labels:
      traefik.enable: "true"
      #traefik.http.services.whoami.loadbalancer.server.port: "8081"
      #traefik.http.services.whoami.loadbalancer.server.scheme: "https"
      ##traefik.http.routers.whoami-http.entrypoints: "web"
      ##traefik.http.routers.whoami-http.rule: "Host(`whoami.dajays.com`)"
      traefik.http.routers.whoami-https.entrypoints: "websecure"
      traefik.http.routers.whoami-https.rule: "Host(`whoami.dajays.com`)"
      ##traefik.http.routers.whoami-https.tls: "true"
      traefik.http.routers.whoami-https.tls.certresolver: "myresolver"
    #networks:
    #  - infrastructure_frontend 

